# Pandas

- Pandas is a Python library used for working with data sets.
- It provides functions for:
  - Analyzing data
  - Cleaning data
  - Exploring data
  - Manipulating data

## Name Origin

- The name **"Pandas"** comes from:
  - **Panel Data**

In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

3.0.2

## Panda Series
- A Pandas Series is like a column in a table.

- It is a one-dimensional array holding data of any type.

In [12]:
a = [1,2, "apple"]

series = pd.Series(a, index = ["x", "y", "z"])

print(a)

[1, 2, 'apple']

In [16]:
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64

# DataFrames in Pandas

- A Pandas DataFrame is a two-dimensional, tabular data structure in Python that organizes data into rows and columns.

In [23]:
data = {
    "name" : ["Jay", "John", "Mike", "Priya"],
    "age" : [23, 34, None, 19],
    "Married": [False, True, False, False],
    "weight": [65.7, 75.2, 88.9, None]
}

df = pd.DataFrame(data)

print(df.columns)
print()
print(df)

Index(['name', 'age', 'Married', 'weight'], dtype='str')

    name   age  Married  weight
0    Jay  23.0    False    65.7
1   John  34.0     True    75.2
2   Mike   NaN    False    88.9
3  Priya  19.0    False     NaN

# loc vs iloc in Pandas

- Both are used to access rows and columns in a DataFrame.

| Method | Works With |
|---|---|
| `loc[]` | Labels / Names |
| `iloc[]` | Integer Positions |

### Examples

```python
df.loc[0]      # Access using label
df.iloc[0]     # Access using position

In [36]:
df.loc[:, "name"]

0      Jay
1     John
2     Mike
3    Priya
Name: name, dtype: str

In [48]:
# Custom rows and columns fetching

df.loc[[0, 2],["name","Married"]]

   name  Married
0   Jay    False
2  Mike    False

In [34]:
df.iloc[:2, :3]

   name   age  Married
0   Jay  23.0    False
1  John  34.0     True

In [40]:
df.iloc[0:1, 0:1]

  name
0  Jay

In [41]:
print(df.to_string())

    name   age  Married  weight
0    Jay  23.0    False    65.7
1   John  34.0     True    75.2
2   Mike   NaN    False    88.9
3  Priya  19.0    False     NaN

## Information about DataFrame

In [42]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     4 non-null      str
 1   age      3 non-null      float64
 2   Married  4 non-null      bool
 3   weight   3 non-null      float64
dtypes: bool(1), float64(2), str(1)
memory usage: 248.0 bytes
None

### Describe numeric columns in DataFrame

In [43]:
print(df.describe())

             age    weight
count   3.000000   3.00000
mean   25.333333  76.60000
std     7.767453  11.66319
min    19.000000  65.70000
25%    21.000000  70.45000
50%    23.000000  75.20000
75%    28.500000  82.05000
max    34.000000  88.90000

### Check for missing values in DataFrame

In [46]:
df.isna().sum() # or df.isnull().sum()

name       0
age        1
Married    0
weight     1
dtype: int64

### Check for duplicate rows in DataFrame

In [52]:
len(df[df.duplicated()])

0